language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install virtualenv==15.2.0; fi
  - pip install -r test-requirements.txt
  - pip install -r requirements.txt
  - pip install tox-travis

script:
  - tox

after_success:
  - coveralls
